spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      routes:
        ## auth service
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        ## user service
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - name: Authentication

        ## event service
        - id: event
          uri: lb://event-service
          predicates:
            - Path=/events/**
          filters:
            - name: Authentication
            
        ## hall of fame service
        - id: hof
          uri: lb://hof-service
          predicates:
            - Path=/hof/**
          filters:
            - name: Authentication
   
        ## news service
        - id: news
          uri: lb://news-service
          predicates:
            - Path=/news/**
          filters:
            - name: Authentication

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka