spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      routes:
        ## auth service
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        ## user service
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - name: Authentication
            
        ## news service
        - id: news
          uri: lb://news-service
          predicates:
            - Path=/news/**
          filters:
            - name: Authentication
#
#        ## Service2
#        - id: service2
#          uri: lb://service2
#          predicates:
#            - Path=/service2/**
#          filters:
#            - StripPrefix=1

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka